### ISSUE TITLE
IP Blacklists Functionality

### ISSUE THREAD

**Issue by ghost** [openemr/docker-madness#1]
There are many good IP blacklists on the internet that are updated daily.

Generate a list of IP's daily, and then have rules in Docker for blocking these IPs.

1. I think IPTables will need to be used.
2. I think IPTables will be fast enough. Maybe use IPSets but not sure if possible with Docker.
3. Can also block at the Web Server level via Apache, and can create things like map files for fast read times.

**Comment by danehrlich1** [comment]
1. Blocking at the Apache Web Server level via `mod_rewrite` and using fast lookup dbm files. [This answer](https://stackoverflow.com/a/15580768/1492590) is basically what I did. Is quite fast. I fetch the IP Blacklists txt file daily via cron, convert it to dbm file using `httxt2dbm`, and then place it in /etc/apache2 as read-only. 

2. Can also block by using IPTables and IPsets, but requires issuing a `docker run` command that includes `--cap-add=NET_ADMIN`. Might do this later, if only because there are really good scripts written for this + defense-in-depth.

**Comment by ghost** [comment]
Done

**Comment by robertdown** [comment]
Could this be built in a way that just runs as a "non work-hours process." I tell Windows when acceptable update time frames are so I'm not getting updates in the middle of work.
